<a href="https://colab.research.google.com/github/humbertozanetti/estruturadedados/blob/main/Notebooks/Estrutura_de_Dados_Aula_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ESTRUTURA DE DADOS - AULA 03**
# **Prof. Dr. Humberto A. P. Zanetti**
# Fatec Deputado Ary Fossen - Jundiaí


---

**Conteúdo da aula:**
+ NumPy
  - Vetores
  - Matrizes
+ Introdução a manipulação de arquivos





---

# **A biblioteca NumPy**

A biblioteca **NumPy** (*Numerical Python*) é especializada em computação númerica, incluindo o trabalho com **arrays** (vetores) e **matrizes** e possui uma grande coleção de funções matemáticas eficientes para operações em larga escala.
Entre as principais vantagens do uso do NumPy, destacam-se:
+ Melhor desempenho que listas Python para operações matemáticas.
+ Usa menos memória para armazenar dados.
+ Possui operações vetorizadas que eliminam a necessidade de loops explícitos.
+ Integração com outras bibliotecas científicas, como Pandas, Matplotlib e SciPy.

Muito simples e objetivo ao uso, como podemos ver abaixo:

In [1]:
import numpy as np

vetor = np.array([1, 2, 3, 4, 5])
print(vetor)


[1 2 3 4 5]


## **Por que estudar vetores e matrizes, além das listas?**

Vetores são mais eficientes e rápidos porque armazenam elementos de mesmo tipo e usam operações otimizadas, desenvolvidas em C (interligando o kernel CPython).  
Listas em Python são mais flexíveis, mas menos eficientes, pois armazenam objetos genéricos, e com isso, utilizam mais memória.  
Vetores e matrizes trazem vantagens em relação a busca, ordenação, entre outras operações, em relação à listas.  
Isso é muito nítido, até mesmo em um simples código podemos notar:

In [2]:
import numpy as np
import time

lista = list(range(1_000_000))
array = np.array(lista)

inicio_lista = time.time()
[lista[i] * 2 for i in range(len(lista))]
print('Tempo lista:', time.time() - inicio_lista)

inicio_array = time.time()
array * 2
print('Tempo array:', time.time() - inicio_array)


Tempo lista: 0.10863208770751953
Tempo array: 0.0035948753356933594


![listaxarray](https://github.com/humbertozanetti/estruturadedados/blob/main/Notebooks/imagens/listaxarray.png?raw=1)


| Característica | Array	| Lista |   
| :------------ | :---:  | :---: |
| **Eficiência** |	Alta (mais rápido) | 	Baixa (mais lento) |
| **Tipos de dados** | Um único tipo	| Qualquer tipo |
| **Operações matemáticas** |	Vetorizadas (rápidas) |	Precisa de loops |
| **Uso de memória** |	Menor	| Maior |

Nessa aula não é possível abordar tudo o que há no Numpy, mas ele possui um excelente [documentação](https://numpy.org/doc/2.2/reference/index.html) e um [manual](https://numpy.org/doc/2.2/numpy-user.pdf) bem organizado.

## **Criando vetores e matrizes**

Como visto anteriormente, um vetor em NumPy é criado a partir de **uma lista**.

In [3]:
import numpy as np

vetor = np.array([1, 2, 3, 4, 5])
print(vetor)

[1 2 3 4 5]


E é igualmente simples criar uma matriz, também a partir de uma lista (de listas).

In [6]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)


[[1 2 3]
 [4 5 6]]


Uma particularidade que deve ser notada é que se cria um **vetor** após a inserção da lista, mas ainda temos que seguir a regra que **um vetor deve ser homogêneo, ou seja, com todos os elementos do mesmo tipo!**

In [7]:
vetor = np.array([1, 2, 3, 4, 5.0])
print(vetor)

[1. 2. 3. 4. 5.]


Um potencial de uso da NumPy é a coleção de propriedades que temos ao utilizá-la.

In [8]:
print(vetor.shape)   # tamanho do vetor
print(matriz.shape)  # dimensão da matriz
print(vetor.ndim)    # número de dimensões
print(matriz.ndim)
print(vetor.size)    # número total de elementos
print(matriz.size)


(5,)
(2, 3)
1
2
5
6


Podemos também usar funções especiais de criação de vetores e matrizes.  

In [9]:
print(np.zeros(5))          # vetor com 5 zeros
print(np.zeros((2, 3)))     # matriz 2x3 de zeros
print(np.ones((3, 3)))      # matriz 3x3 de uns
print(np.eye(3))            # matriz identidade 3x3
print(np.arange(0, 10, 2))  # sequência de 0 a 10 com passo 2
print(np.linspace(0, 1, 5)) # 5 valores igualmente espaçados entre 0 e 1


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [10]:
mat_ide = np.eye(3)
print(mat_ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## **Operações matemáticas**

Um dos maiores destaques do uso de NumPy é a possibilidade de executar operações de forma muito mais ágil e sem uso de laços de repetição.

**Operação elemento a elemento**

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a + 10)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[11 12 13]


**Multiplicação de matrizes**

In [14]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

produto = np.dot(matriz1, matriz2)
print(produto)


[[19 22]
 [43 50]]


**Funções estatísticas**

In [15]:
dados = np.array([5, 10, 15, 20, 25])

print(np.mean(dados))   # Média
print(np.median(dados)) # Mediana
print(np.std(dados))    # Desvio padrão
print(np.sum(dados))    # Soma total
print(np.max(dados))    # Máximo
print(np.min(dados))    # Mínimo


15.0
15.0
7.0710678118654755
75
25
5


Exemplo:

In [16]:
temperaturas = np.array([25, 27, 26, 30, 28, 29, 31])
print(f'Média da semana: {np.mean(temperaturas):.2f}°C')

Média da semana: 28.00°C


## **Indexação e fatiamento**

Assim como em listas, podemos trabalhar com os índices e fatiamento.

**Fatiamento**

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])    # Primeiro elemento
print(arr[-1])   # Último elemento
print(arr[1:4])  # Elementos do índice 1 ao 3

10
50
[20 30 40]


In [18]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)
print(matriz[0, 1])   # Elemento na primeira linha, segunda coluna
print(matriz[:, 1])   # Segunda coluna inteira
print(matriz[1, :])   # Segunda linha inteira

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[2 5 8]
[4 5 6]


Podemos também acessar os elementos individualmente, como em lsitas, utilizando **for**.

In [19]:
vetor = np.array([10, 20, 30, 40, 50])

for elemento in vetor:
    print(elemento)

10
20
30
40
50


Há também uma função específica para isso, a `ndinter()`.

In [20]:
for elemento in np.nditer(vetor):
    print(elemento)

10
20
30
40
50


A função `enumerate()` também funciona com NumPy.

In [21]:
for i, elemento in enumerate(vetor):
    print(f'Índice {i}: {elemento}')

Índice 0: 10
Índice 1: 20
Índice 2: 30
Índice 3: 40
Índice 4: 50


Com matrizes também funcionam.

In [23]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

for linha in matriz:
    print(linha)

[1 2 3]
[4 5 6]
[7 8 9]


In [22]:
for linha in matriz:
    for elemento in linha:
        print(elemento, end=' ')

1 2 3 4 5 6 7 8 9 

In [24]:
for elemento in np.nditer(matriz):
    print(elemento, end=' ')

1 2 3 4 5 6 7 8 9 

In [25]:
for i, linha in enumerate(matriz):
    print(f'Linha {i}: {linha}')

Linha 0: [1 2 3]
Linha 1: [4 5 6]
Linha 2: [7 8 9]


In [26]:
linhas, colunas = matriz.shape

for i in range(linhas):
    for j in range(colunas):
        print(f'Elemento[{i},{j}] = {matriz[i, j]}')

Elemento[0,0] = 1
Elemento[0,1] = 2
Elemento[0,2] = 3
Elemento[1,0] = 4
Elemento[1,1] = 5
Elemento[1,2] = 6
Elemento[2,0] = 7
Elemento[2,1] = 8
Elemento[2,2] = 9


# **Manipulação de arquivos**

Utilizar uma biblioteca como a NumPy faz mtuio sentido quando lidamos com grande número de dados. Geralmente essa grande massa de dados está associada à um base externa, como um arquivo.  
A biblioteca NumPy é preparada para atuar com arquivos estruturados de dados, como o formato **.csv** (*Comma-Separated Values* ou Valores Separados por Vírgulas), comum em editores de planilhas.  
Para praticar durante a aula, vamos fazer um script de criação de um arquivo `dados.csv`. Esse arquivo ficará acessível para nosso notebook e se encontra na aba **arquivos** (ícone de pasta, ao lado esquerdo).

```
10,20,30
40,50,60
70,80,90
```


In [4]:
with open('dados.csv', 'w') as f:
    f.write('10,20,30\n40,50,60\n70,80,90\n')

Para carregar um arquivo de dados é bem simples em NumPy:

In [28]:
dados = np.loadtxt('dados.csv', delimiter=',')
print(dados)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


Note que o formato CSV o separador vírgula é definido como um argumento nomeado `delimiter`.  
Depois dessa simples instrução, a matriz `dados` terá os dados, separados por linha e coluna. Com isso, podemos fazer algumas operações estatísticas com esses dados.

In [29]:
print(f'Média: {np.mean(dados)}')
print(f'Máximo: {np.max(dados)}')
print(f'Mínimo: {np.min(dados)}')
print(f'Soma de todos os valores: {np.sum(dados)}')

Média: 50.0
Máximo: 90.0
Mínimo: 10.0
Soma de todos os valores: 450.0


E filtros:

In [30]:
dados = np.loadtxt('dados.csv', delimiter=',')
filtro = dados > 30
print(dados[filtro])  # Mostra apenas os valores maiores que 30

[40. 50. 60. 70. 80. 90.]


Também é possível possível salvar novamente, em até mesmo em um arquivo diferente:

In [31]:
np.savetxt('dados_processados.csv', dados * 2, delimiter=',', fmt='%.2f')

**EXERCÍCIOS**

1. Crie um vetor contendo números de 1 a 1000, e depois:
  + Eleve todos os elementos ao quadrado.
  + Filtre e exiba apenas os valores maiores que 30.
  + Calcule e exiba a média e o desvio padrão do vetor resultante.

**Dica:** explore o seguinte comando: `vetor_int = np.random.randint(1, 10, size=5)`


In [32]:
vetor_int = np.random.randint(1,1000,size = 50)
print(vetor_int)

vetor_int = vetor_int**2
print(vetor_int)

filtro = vetor_int > 30
filtrado = vetor_int[filtro]

print(np.mean(filtrado))
print(np.std(filtrado))

[486 758 603 981 974 562   9 990 688  53 125 199 625  44 490 310 231  94
 186 462 998 706 459 193 475 808 633 211 461 582 429 714 595 158  96 802
 651 912 513 388 415 115 966 261 791  81 271 532  60 659]
[236196 574564 363609 962361 948676 315844     81 980100 473344   2809
  15625  39601 390625   1936 240100  96100  53361   8836  34596 213444
 996004 498436 210681  37249 225625 652864 400689  44521 212521 338724
 184041 509796 354025  24964   9216 643204 423801 831744 263169 150544
 172225  13225 933156  68121 625681   6561  73441 283024   3600 434281]
311538.82
300011.563536987


2. Crie uma matriz 3x3 com números inteiros aleatórios entre 100 e 999.  
  + Exiba a matriz gerada.
  + Calcule e exiba a soma de todos os elementos da matriz.
  + Encontre e exiba o maior e o menor valor da matriz.
  + Calcule e exiba a média dos valores de cada linha.
   

**Dica:** explore o seguinte comando: `matriz_int = np.random.randint(1, 100, size=(2, 2))`



In [33]:
matriz = np.random.randint(100,999,size=(3,3))
print(matriz)
print(np.sum(matriz))
print(np.max(matriz), np.min(matriz))

for linha in matriz:
  print(np.mean(linha))

[[967 831 118]
 [979 995 560]
 [691 301 619]]
6061
995 118
638.6666666666666
844.6666666666666
537.0


3. Ler uma matriz de um arquivo CSV.
  + Inverter a matriz original usando NumPy.
  + Salvar a matriz invertida em um novo arquivo CSV.
  + Zerar (colocar zeros) na diagonal principal da matriz original
  + Salvar a matriz com a diagonal zerada em um novo arquivo CSV.

  **Dicas**:
  + Existem as funções `linalg.det()`, que mostra o determinante; e a função `linalg.inv()`, para geração matriz invertida. Pesquise o uso dessas funções;
  + Existe a função `fill_diagonal()`, pesquise como usar.

In [ ]:
import numpy as np

with open('matriz.csv', 'w') as f:
  f.write('2,1,0\n0,1,0\n1,2,1\n')
  #f.write('1,2,3\n4,5,6\n7,8,9\n')

matriz = np.loadtxt('matriz.csv', delimiter=',')
print('Matriz original:')
print(matriz)
# Verificar se a matriz pode ser invertida (determinante diferente de zero)
if np.linalg.det(matriz) == 0:
    print('Erro: A matriz não é inversível (determinante igual a zero).')
else:
    # Inverte a matriz
    matriz_invertida = np.linalg.inv(matriz)
    print('Matriz Invertida:')
    print(matriz_invertida)

    np.savetxt('matriz_invertida.csv', matriz_invertida, delimiter=',', fmt='%.2f')